version: "3.8"

services:
  server:
    container_name: app
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    restart: always
